### ISSUE TITLE
VR Frozen in Fullscreen?

### ISSUE THREAD

**Issue by itsalljustaride** [kevinbazira/algori-360-image#2]
I have tried in both Chrome v 79.0.3945.130 and Firefox v 68.4.2esr and in both the VR image is not interactive in fullscreen mode.

*edit* Also tried updating Chrome to v 80.0.3987.87 and also has same issue.

**Comment by itsalljustaride** [comment]
Upgrading aframe to v1.0.4 seems to fix it, but needs to be confirmed.

**Comment by kevinbazira** [comment]
Hi @itsalljustaride ,

Thank you for using the Algori 360 Image plugin.

Please upgrade to Algori 360 Image v1.0.7 where the VR mode / full screen mouse drag issue was fixed.

Enjoy!
